version: '3.8'

services:
  nginx:
    image: nginx:1.28.0
    ports:
      - "90:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  composer:
    image: composer:2.8.8
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - composer_cache:/tmp
    entrypoint: [ "composer" ]

volumes:
  postgres_data:
  composer_cache: