<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250512215101 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Create user and role tables';
	}

	public function up(Schema $schema): void
	{
		$this->addSql(
			'CREATE TABLE "user" (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                surname VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL,
                password VARCHAR(255) NOT NULL,
                last_login_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            );'
		);

		$this->addSql(
			'CREATE TABLE role (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                PRIMARY KEY(id)
            );'
		);
	}

	public function down(Schema $schema): void
	{
		$this->addSql('DROP TABLE role;');
		$this->addSql('DROP TABLE "user";');
	}
}
